config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  # Путь для админки
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Пути для формы регистрации, входа и т.д.
  devise_for :users

  # в профиле юзера показываем его игры, на главной - список лучших игроков
  resources :users, only: [:index, :show]

  resources :games, only: [:create, :show] do
    # доп. методы ресурса:
    put 'help', on: :member # помощь зала
    put 'answer', on: :member # ответ на текущий вопрос
    put 'take_money', on: :member #  игрок берет деньги
  end

  # Ресурс в единственном числе - ВопросЫ
  # для загрузки админом сразу пачки вопросОВ
  resource :questions, only: [:new, :create]
end

app/models/question.rb
class Question < ApplicationRecord

  QUESTION_LEVELS = (0..14).freeze

  # у вопроса должен быть уровень сложности
  validates :level, presence: true, inclusion: {in: QUESTION_LEVELS}

  # Текст вопроса (не может быть пустым и не должен повторяться, иначе смысл?)
  validates :text, presence: true, uniqueness: true, allow_blank: false

  # Варианты ответов (в первом всегда храним правильный)
  validates :answer1, :answer2, :answer3, :answer4, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin!

  def new
  end

  def create
    level = params[:questions_level].to_i
    q_file = params[:questions_file]

    if q_file.respond_to?(:readlines)
      file_lines = q_file.readlines
    elsif q_file.respond_to?(:path)
      file_lines = File.readlines(q_file.path)
    else
      redirect_to new_questions_path, alert: "Bad file_data: #{q_file.class.name}, #{q_file.inspect}"
      return false
    end

    start_time = Time.now
    failed_count = create_questions_from_lines(file_lines, level)

    redirect_to new_questions_path,
                notice: "Уровень #{level}, обработано #{file_lines.size}," +
                  " создано #{file_lines.size - failed_count}," +
                  " время #{Time.at((Time.now - start_time).to_i).utc.strftime '%S.%L сек'}"
  end

  private

  def authorize_admin!
    redirect_to root_path unless current_user.is_admin
  end

  def create_questions_from_lines(lines, level)
    failed = 0
    ActiveRecord::Base.transaction do
      lines.each do |line|
        ar = line.split('|')
        q = Question.create(
          level: level,
          text: ar[0].squish,
          answer1: ar[1].squish,
          answer2: ar[2].squish,
          answer3: ar[3].squish,
          answer4: ar[4].squish
        )
        failed += 1 unless q.valid?
      end
    end
    failed
  end
end

app/views/questions/new.html.erb
<%= form_tag questions_path, multipart: true do %>

  <div>
    <h3 class="buffer-bottom">
      Укажите уровень пачки вопросов и приложите файл нужного формата
    </h3>
    <p>
      <em>Каждая непустая строка файла должна выглядеть так:</em>
    </p>
    <p>
      <code>
        Текст вопроса?|Правильный ответ|Ответ 2|Ответ 3|Ответ 4
      </code>
    </p>
  </div>
  <div class="field buffer-top">
    <%= label_tag "Уровень — #{Question::QUESTION_LEVELS}" %><br>
    <%= text_field_tag :questions_level %>
  </div>
  <div class="field buffer-top">
    <%= label_tag 'Файл с вопросами' %><br>
    <%= file_field_tag :questions_file %>
  </div>

  <div class="actions buffer-top">
    <%= submit_tag %>
  </div>
<% end %>