config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  # Путь для админки
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Пути для формы регистрации, входа и т.д.
  devise_for :users

  # в профиле юзера показываем его игры, на главной - список лучших игроков
  resources :users, only: [:index, :show]

  resources :games, only: [:create, :show] do
    # доп. методы ресурса:
    put 'help', on: :member # помощь зала
    put 'answer', on: :member # ответ на текущий вопрос
    put 'take_money', on: :member #  игрок берет деньги
  end

  # Ресурс в единственном числе - ВопросЫ
  # для загрузки админом сразу пачки вопросОВ
  resource :questions, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_validation :set_name, on: :create

  # имя не пустое, email валидирует Devise
  validates :name, presence: true

  # поле только булевское (лож/истина) - недопустимо nil
  validates :is_admin, inclusion: {in: [true, false]}, allow_nil: false

  # это поле должно быть только целым числом, значение nil - недопустимо
  validates :balance, numericality: {only_integer: true}, allow_nil: false

  # у юзера много игр, они удалятся из базы вместе с ним
  has_many :games, dependent: :destroy

  # расчет среднего выигрыша по всем играм юзера
  def average_prize
    (balance.to_f/games.count).round unless games.count.zero?
  end

  def set_name
    self.name = "Игрок №#{rand(777)}" if self.name.blank?
  end
end

app/controllers/users_controller.rb
# (c) goodprogrammer.ru
#
# Контроллер, отображающий список и профиль юзера
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    # Для страницы рейтинга нам понадобятся все пользователи, остортированные по выигрышу
    @users = User.all.order(balance: :desc)
  end

  def show
    # Для профиля пользователя нам понадобятся всего игры в порядке давности
    @games = @user.games.order(created_at: :desc)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_game.html.erb
<%# Шаблон, который выводит информацию о конкретной игре для профиля пользователя %>
<tr class="text-center">
  <td><%= game.id %></td>
  <td><%= game_label(game) %></td>
  <td><%= l game.created_at, format: :short %></td>
  <td><%= game.current_level %></td>
  <td><%= number_to_currency game.prize %></td>
  <td>
    <%= content_tag :span, '50/50',
      class: "label label-primary #{'game-help-used' if game.fifty_fifty_used?}"
    %>
    <%= content_tag :span, 'phone',
      class: "label label-primary #{'game-help-used' if game.friend_call_used?}"
    %>
    <%= content_tag :span, 'users',
      class: "label label-primary #{'game-help-used' if game.audience_help_used?}"
    %>
  </td>
</tr>

app/views/users/index.html.erb
<h1 class="text-light">Рейтинг</h1>

<div class="row">
<div class="col-md-8 col-md-offset-2">
  <table class="users-table table bg-white p-2 text-dark bg-opacity-50">
    <thead>
      <tr>
        <th class="text-center">Место</th>
        <th class="text-center">Имя</th>
        <th class="text-center">Выигрыш</th>
        <th class="text-center">Игр</th>
        <th class="text-center">За игру</th>
      </tr>
    </thead>

    <%# Для каждого пользователя выводим информацию о его выигрыше, ссылку на профиль и так далее %>
    <% @users.each_with_index do |user, index| %>
      <tr class="text-center">
        <td><%= index + 1 %></td>
        <td><%= link_to user.name, user_path(user), class: "text-dark" %></td>
        <td><%= number_to_currency user.balance %></td>
        <td><%= user.games.count %></td>
        <td><%= user.average_prize %></td>
      </tr>
    <% end %>
  </table>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
<div class="col-md-8 col-md-offset-2">
  <div>
    <h1 class="text-light"><%= @user.name %></h1>
    <%= link_to 'Сменить имя и пароль', edit_user_registration_path(@user) if @user == current_user %>
  </div>
  <table class="users-table table bg-white p-2 text-dark bg-opacity-50 mt-3">
    <thead>
      <tr>
        <th class="text-center">#</th>
        <th></th>
        <th class="text-center">Дата</th>
        <th class="text-center">Вопрос</th>
        <th class="text-center">Выигрыш</th>
        <th class="text-center">Подсказки</th>
      </tr>
    </thead>

    <%# Выводим список игр пользователя с помощью нашего фрагмента users/_game %>
    <%= render partial: 'game', collection: @games %>
  </table>
</div>
</div>