config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  # Путь для админки
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Пути для формы регистрации, входа и т.д.
  devise_for :users

  # в профиле юзера показываем его игры, на главной - список лучших игроков
  resources :users, only: [:index, :show]

  resources :games, only: [:create, :show] do
    # доп. методы ресурса:
    put 'help', on: :member # помощь зала
    put 'answer', on: :member # ответ на текущий вопрос
    put 'take_money', on: :member #  игрок берет деньги
  end

  # Ресурс в единственном числе - ВопросЫ
  # для загрузки админом сразу пачки вопросОВ
  resource :questions, only: [:new, :create]
end

app/models/game.rb
class Game < ApplicationRecord

  # денежный приз за каждый вопрос
  PRIZES = [
    100, 200, 300, 500, 1000,
    2000, 4000, 8000, 16000, 32000,
    64000, 125000, 250000, 500000, 1000000
  ].freeze

  FIREPROOF_LEVELS = [4, 9, 14].freeze

  TIME_LIMIT = 35.minutes

  belongs_to :user

  has_many :game_questions, dependent: :destroy

  validates :user, presence: true

  validates :current_level, numericality: {only_integer: true}, allow_nil: false

  validates :prize,
            presence: true,
            numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: PRIZES.last}

  scope :in_progress, -> { where(finished_at: nil) }

  def self.create_game_for_user!(user)
    transaction do
      game = create!(user: user)

      Question::QUESTION_LEVELS.each do |i|
        q = Question.where(level: i).order('RANDOM()').first
        ans = [1, 2, 3, 4]
        game.game_questions.create!(question: q, a: ans.shuffle!.pop, b: ans.shuffle!.pop, c: ans.shuffle!.pop, d: ans.shuffle!.pop)
      end
      game
    end
  end

  def previous_game_question
    game_questions.detect { |q| q.question.level == previous_level }
  end

  def current_game_question
    game_questions.detect { |q| q.question.level == current_level }
  end

  def previous_level
    current_level - 1
  end

  def finished?
    finished_at.present?
  end

  def time_out!
    if (Time.now - created_at) > TIME_LIMIT
      finish_game!(fire_proof_prize(previous_level), true)
      true
    end
  end

  def answer_current_question!(letter)
    return false if time_out! || finished?

    if current_game_question.answer_correct?(letter)
      if current_level == Question::QUESTION_LEVELS.max
        self.current_level += 1
        finish_game!(PRIZES[Question::QUESTION_LEVELS.max], false)
      else
        self.current_level += 1
        save!
      end

      true
    else
      finish_game!(fire_proof_prize(previous_level), true)
      false
    end
  end

  def take_money!
    return if time_out! || finished? # из законченной или неначатой игры нечего брать
    finish_game!((previous_level > -1) ? PRIZES[previous_level] : 0, false)
  end

  def use_help(help_type)
    case help_type
    when :fifty_fifty
      unless fifty_fifty_used
        # ActiveRecord метод toggle! переключает булевое поле сразу в базе
        toggle!(:fifty_fifty_used)
        current_game_question.add_fifty_fifty
        return true
      end
    when :audience_help
      unless audience_help_used
        toggle!(:audience_help_used)
        current_game_question.add_audience_help
        return true
      end
    when :friend_call
      unless friend_call_used
        toggle!(:friend_call_used)
        current_game_question.add_friend_call
        return true
      end
    end
    false
  end

  def status
    return :in_progress unless finished?

    if is_failed
      if (finished_at - created_at) <= TIME_LIMIT
        :fail
      else
        :timeout
      end
    else
      if current_level > Question::QUESTION_LEVELS.max
        :won
      else
        :money
      end
    end
  end

  private

  def finish_game!(amount = 0, failed = true)
    transaction do
      self.prize = amount
      self.finished_at = Time.now
      self.is_failed = failed
      user.balance += amount
      save!
      user.save!
    end
  end

  def fire_proof_prize(answered_level)
    lvl = FIREPROOF_LEVELS.select { |x| x <= answered_level }.last
    lvl.present? ? PRIZES[lvl] : 0
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :goto_game_in_progress!, only: [:create]
  before_action :set_game, except: [:create]
  before_action :redirect_from_finished_game!, except: [:create]

  def show
    @game_question = @game.current_game_question
  end

  def create
    begin
      @game = Game.create_game_for_user!(current_user)
      redirect_to game_path(@game), notice: I18n.t('controllers.games.game_created', created_at: @game.created_at)

    rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotSaved => ex
      Rails.logger.error("Error creating game for user #{current_user.id}, msg = #{ex}. #{ex.backtrace}")
      redirect_back fallback_location: root_path, alert: I18n.t('controllers.games.game_not_created')
    end
  end

  def answer
    @answer_is_correct = @game.answer_current_question!(params[:letter])
    @game_question = @game.current_game_question

    unless @answer_is_correct
      flash[:alert] = I18n.t(
        'controllers.games.bad_answer',
        answer: @game_question.correct_answer,
        prize: view_context.number_to_currency(@game.prize)
      )
    end

    respond_to do |format|
      format.html do
        if @answer_is_correct && !@game.finished?
          redirect_to game_path(@game)
        else
          redirect_to user_path(current_user)
        end
      end

      format.js {}
    end
  end

  def take_money
    @game.take_money!
    redirect_to user_path(current_user),
                flash: { warning: I18n.t('controllers.games.game_finished', prize: view_context.number_to_currency(@game.prize)) }
  end

  def help
    msg = if @game.use_help(params[:help_type].to_sym)
            { flash: { info: I18n.t('controllers.games.help_used') } }
          else
            { alert: I18n.t('controllers.games.help_not_used') }
          end

    redirect_to game_path(@game), msg
  end

  private

  def redirect_from_finished_game!
    redirect_to user_path(current_user), alert: I18n.t('controllers.games.game_closed', game_id: @game.id) if @game.finished?
  end

  def goto_game_in_progress!
    game_in_progress = current_user.games.in_progress.first
    redirect_to game_path(game_in_progress), alert: I18n.t('controllers.games.game_not_finished') unless game_in_progress.blank?
  end

  def set_game
    @game = current_user.games.find_by(id: params[:id])
    redirect_to root_path, alert: I18n.t('controllers.games.not_your_game') if @game.blank?
  end
end

app/helpers/games_helper.rb
# Этот файл будет автоматически загружен при отрисовке шаблона
# Мы будем складывать в него все вспомогательные методы, которые захотим использовать в шаблонах,
# связаныхх с отображением игр
module GamesHelper
  # Этот метод будет рисовать удобный ярлычок для показа статуса игры
  # Используем стандартные bootstrap-овский класс `label`
  def game_label(game)
    if game.status == :in_progress && current_user == game.user
      link_to content_tag(:span, t("game_statuses.#{game.status}"), class: 'label'), game_path(game)
    else
      content_tag :span, t("game_statuses.#{game.status}"), class: 'label label-danger'
    end
  end
end

app/views/games/_game_question.html.erb
<% game = game_question.game %>
<% help = game_question.help_hash %>

<div class="bg-white p-2 text-dark bg-opacity-50 rounded text-center">
  <h2 class="my-2"><%= game_question.text %></h2>
</div>

<div class="row mt-3">
  <% game_question.variants.each do |letter, variant| %>
    <% if !help.key?(:fifty_fifty) || help[:fifty_fifty].include?(letter) %>
      <div class="d-grid gap-2 col-6 mx-auto">
        <%= link_to content_tag(:span, letter.upcase, class: 'variant') + ": #{variant}",
                    answer_game_path(game, letter: letter),
                    data: { turbo_method: "put" },
                    remote: true,
                    class: 'btn btn-outline-light my-3'
        %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/games/_help.html.erb
<div class="game-help-info">
  <% if help.key?(:friend_call) || help.key?(:audience_help) %>
    <div class="row buffer-top-lg">
      <div class="col-xs-12">
        <% if help.key?(:friend_call) %>
          <div class="alert alert-info text-center">
            <%= help[:friend_call] %>
          </div>
        <% end %>

        <% if help.key?(:audience_help) %>
          <p>Зрители считают: </p>
          <% help[:audience_help].sort.map do |key, value| %>
            <div class="progress">
              <div class="progress-bar progress-bar-danger" style="width: <%= value %>%;">
                <%= key.upcase %>: <%= value %>%
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="game-help row my-5">
  <div class="col-sm-4">
    <% unless game.fifty_fifty_used? %>
      <%= link_to ' 50/50', help_game_path(game, help_type: :fifty_fifty), data: { turbo_method: "put" }, class: 'btn btn-sm btn-warning bi bi-signpost-split mb-1' %>
    <% end %>
  </div>
  <div class="col-sm-4">
    <% unless game.friend_call_used? %>
      <%= link_to ' phone', help_game_path(game, help_type: :friend_call), data: { turbo_method: "put" }, class: 'btn btn-sm btn-warning bi bi-phone-vibrate mb-1' %>
    <% end %>
  </div>
  <div class="col-sm-4">
    <% unless game.audience_help_used? %>
      <%= link_to ' users', help_game_path(game, help_type: :audience_help), data: { turbo_method: "put" }, class: 'btn btn-sm btn-warning bi bi-people mb-1' %>
    <% end %>
  </div>
</div>

app/views/games/answer.js.erb
<%# Этот js-код будет выполнен прямо на странице игры, используя информацию от сервера %>

<% if @answer_is_correct && !@game.finished? %>
  $('.game-question').html("<%= escape_javascript (
      render partial: 'game_question', object: @game_question
    ) %>");

  current_prize = $('.game-prizes').find('.active').toggleClass('active');
  current_prize.prev().toggleClass('active');

  $('.game-help-info').hide();
<% else %>
  window.location.href = '<%= user_path(current_user) %>';
<% end %>

app/views/games/show.html.erb
<div class="row">
  <div class="col-sm-9 col-sm-push-3">
    <div class="text-center my-xl-5">
      <%= image_tag asset_path('logo.png'), class: 'game-logo' %>
    </div>

    <div class="game-question">
      <%# Выводим шаблон с текстом вопроса и вариантами ответа %>
      <%= render partial: 'game_question', object: @game_question %>
    </div>

    <div class="buffer-top-lg">
      <%# Выводим шаблон с кнопками для подсказок и информацией о подсказках %>
      <%= render partial: 'help', object: @game_question.help_hash, locals: {game: @game} %>
    </div>
  </div>

  <div class="col-sm-3 col-sm-pull-9 ">
    <ul class="list-group list-group-prizes game-prizes">
      <% Game::PRIZES.reverse.each_with_index do |prize, index| %>
        <li class="list-group-item text-center bg-white p-2 text-dark bg-opacity-50  <%= 'active' if (14 - index == @game.current_level) %>">
          <%= 'diamond' if Game::FIREPROOF_LEVELS.include?(14-index) %>
          <%= prize %>
        </li>
      <% end %>
    </ul>

    <%= link_to 'Забрать выигрыш', take_money_game_path(@game), data: { turbo_method: "put" }, class: 'btn btn-sm btn-info my-4 ' %>
  </div>
</div>