config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  # Путь для админки
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Пути для формы регистрации, входа и т.д.
  devise_for :users

  # в профиле юзера показываем его игры, на главной - список лучших игроков
  resources :users, only: [:index, :show]

  resources :games, only: [:create, :show] do
    # доп. методы ресурса:
    put 'help', on: :member # помощь зала
    put 'answer', on: :member # ответ на текущий вопрос
    put 'take_money', on: :member #  игрок берет деньги
  end

  # Ресурс в единственном числе - ВопросЫ
  # для загрузки админом сразу пачки вопросОВ
  resource :questions, only: [:new, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MillionerGame</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>
<body>

<div class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <div class="container">
    <%= link_to 'Millioner', root_path, class: 'navbar-brand' %>
    <% if user_signed_in? %>
      <div class="navbar-form navbar-right">

        <% if current_user.is_admin? %>
          <%= link_to 'Админка', rails_admin_path, class: 'btn navbar-btn btn-danger btn-xs' %>
          <%= link_to 'Залить новые вопросы', new_questions_path, class: 'btn navbar-btn btn-warning btn-xs' %>
        <% end %>


        <%= link_to content_tag(:span, "#{current_user.name} - #{number_to_currency current_user.balance}"),
                    user_path(current_user),
                    class: 'btn btn-outline-light btn-sm me-2'
        %>
        <%= link_to 'Новая игра', games_path, data: { turbo_method: "post" }, class: 'btn btn-success btn-sm me-2' %>
        <span>
          <%= link_to "Выход", destroy_user_session_path, data: { "turbo-method" => :delet }, class: 'btn btn-danger btn-sm me-2' %>
        </span>
      </div>
    <% else %>
      <div class="navbar-form navbar-right">
        <%= link_to 'Войти', new_user_session_path, class: 'btn btn-info btn-sm me-2' %>
        <%= link_to 'Зарегистрироваться', new_user_registration_path, class: 'btn  btn-success btn-sm' %>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <% if notice %>
    <div class="alert alert-success alert-dismissible fade show">
      <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger alert-dismissible fade show">
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <%= yield %>

  <footer class="buffer-top-lg text-right">
    <p>&copy; <%= link_to 'Vladislav Fedotov', 'https://github.com/PhantomVlad' %> 2023</p>
  </footer>
</div>
<%#= yield %>
</body>
</html>